### ISSUE TITLE
Regenerate package.lock so that events-stream 3.3.6 is not being used

### ISSUE THREAD

**Issue by SinS3i** [joaomoreno/gulp-vinyl-zip#14]
PR to fix issue: https://github.com/joaomoreno/gulp-vinyl-zip/pull/13

`flatmap-stream` package was removed due to security related issues and is currently causing your installs to fail.

Relevant:
https://github.com/dominictarr/event-stream/issues/116

**Comment by joaomoreno** [comment]
Thanks for the attention! Done!
