### ISSUE TITLE
src function does not emit error to stream when input is a buffer

### ISSUE THREAD

**Issue by mojavelinux** [joaomoreno/gulp-vinyl-zip#16]
When the src function is called without arguments to accept buffer objects in the stream, the error event is not emitted back to that stream. As a result, there's no way to catch an error reading the contents of the zip.

For example:

```js
vfs.src('no-a-zip-file.txt')
  .pipe(gvzip.src())
  .on('error', (err) => console.log('error reading zip: ' + err.message))
  .pipe(gvzip.dest('out.zip'))
```

The error callback is never invoked. Instead, we see:

```
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: end of central directory record signature not found
    at /project/node_modules/yauzl/index.js:187:14
    at /project/node_modules/yauzl/index.js:631:5
```

The reason has to do with the fact that es.merge does not automatically propagate the error event. Therefore, it must be done explicitly.

I'll submit a PR.

**Comment by joaomoreno** [comment]
Published 2.1.3
