### ISSUE TITLE
Publish 0.0.7!

### ISSUE THREAD

**Issue by lettertwo** [joaomoreno/gulp-vinyl-zip#3]
[gulp-atom-shell](https://github.com/joaomoreno/gulp-atom-shell/blob/master/package.json#L30) is looking for it!

**Comment by joaomoreno** [comment]
Still tackling some Windows bugs, unfortunately...

## 

João

**Comment by lettertwo** [comment]
Ah, sorry, didn't mean to show up randomly making demands—I thought maybe it was just an accidental oversight! Thanks for you work on this and gulp-atom-shell!

**Comment by joaomoreno** [comment]
Published `1.0.x`!
