### ISSUE TITLE
src() should assign uncompressed size to stat.size for files and symbolic links

### ISSUE THREAD

**Issue by mojavelinux** [joaomoreno/gulp-vinyl-zip#32]
When reading an archive, gulp-vinyl-zip has access to the uncompressed size of the entry for files and symbolic links, but does not pass along this information on when creating the stat object for the file. It would be helpful to programs that use gulp-vinyl-zip to extract archives files, and need to know the file size, to be able to access this information without having to resolve the stream to find out.

For symlink, the stat.size should be the length of the path to which it points, which exactly matches the uncompressed size reported by the archive entry.

For other non-file entry types (including directories), the size doesn't have any meaning, so there is no need to assign it.

**Comment by joaomoreno** [comment]
Published in 2.5.0

**Comment by mojavelinux** [comment]
Thanks!! :beers:
