### ISSUE TITLE
.src throws a "EEXIST: file already exists" for folders inside zip when piping to disk with gulp

### ISSUE THREAD

**Issue by philkunz** [joaomoreno/gulp-vinyl-zip#6]
.src throws and error for folders inside zips when piping to disk with gulp:

```
Error: EEXIST: file already exists
```

Example: Use repo with some folders.

``` javascript
var gulp = require("gulp");
var zip = require('gulp-vinyl-zip');
var pr = require("pushrocks");

//Paths and URLs
var myUrlToRepoMasterZip = 'https://github.com/someuser/somerepo/archive/master.zip';
var createBasePath = '/test' 

//download the latest version from github as zip
gulp.task('download',function(cb) {
    pr.remotefile.toFS(myUrlToRepoMasterZip,path.join(createBasePath, 'master.zip'),{},cb);
});
gulp.task('default',['download'], function () {
            var stream = zip.src(path.join(createBasePath,'master.zip'))
                .pipe(gulp.dest(createBasePath));
            return stream;
});
```

**Comment by joaomoreno** [comment]
Definitely looks like the error comes from gulp.dest, when it tries to create files/folders in disk...

**Comment by philkunz** [comment]
But gulp.dest normally handles file structures and multi level relative paths well...

**Comment by joaomoreno** [comment]
Just looked at this, you're right. It somehow missed me that gulp simply skips piping directories. Will simply not pipe them in. Will publish a new version now.

**Comment by philkunz** [comment]
Wonderful! :)

**Comment by joaomoreno** [comment]
Published 1.1.1. Thanks for the help!

**Comment by abdullah353** [comment]
<img width="1110" alt="screen shot 2016-02-09 at 2 20 48 pm" src="https://cloud.githubusercontent.com/assets/1429432/12912180/c8153e22-cf38-11e5-8310-a6c810a9714e.png">

This issue appears some times i don't know why. Below is my package.json file 

``` json

  "devDependencies": {
    "angular": "^1.4.7",
    "browserify": "^11.2.0",
    "connect-livereload": "^0.5.3",
    "del": "^2.2.0",
    "express": "^4.13.3",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-browserify": "^0.5.1",
    "gulp-concat": "^2.6.0",
    "gulp-embedlr": "^0.5.2",
    "gulp-jade": "^1.1.0",
    "gulp-jshint": "^1.11.2",
    "gulp-livereload": "^3.8.1",
    "gulp-load-plugins": "^1.0.0",
    "gulp-rimraf": "^0.2.0",
    "gulp-sass": "^2.0.4",
    "gulp-util": "^3.0.7",
    "jquery": "^2.1.4",
    "tiny-lr": "^0.2.1"
  }
```

**Comment by abdullah353** [comment]
Sorry this issue is resolved and was not related to gulp, I was using "del" module which was removing folder asynchronously. replacing "del" with "del.sync" solved my issue.

**Comment by joaomoreno** [comment]
:+1:
