### ISSUE TITLE
Please uplevel vinyl-fs

### ISSUE THREAD

**Issue by bpasero** [joaomoreno/gulp-vinyl-zip#8]
@joaomoreno You are using vinyl-fs < 1.0 and this drags in outdated versions of graceful-fs etc.

**Comment by joaomoreno** [comment]
Care to contribute a PR? 😛

**Comment by bpasero** [comment]
@joaomoreno https://github.com/joaomoreno/gulp-vinyl-zip/pull/9

You might want to setup Travis to run the tests 👍

**Comment by joaomoreno** [comment]
Fixed by #9

**Comment by joaomoreno** [comment]
Published 1.3.0
